### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by rachitmishra** [freshdesk/hotline-android#11]
```java
A resource was acquired at attached stack trace but never released. 
See java.io.Closeable for information on avoiding resource leaks.

java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.util.zip.Inflater.<init>(Inflater.java:104)
at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
at com.demach.konotor.client.helper.a.a(Unknown Source)
at com.demach.konotor.client.helper.a.m(Unknown Source)
at com.freshdesk.hotline.service.helper.a.a(Unknown Source)
at com.freshdesk.hotline.service.handler.d.a(Unknown Source)
at com.freshdesk.hotline.service.handler.d.b(Unknown Source)
at com.freshdesk.hotline.service.executor.b.b(Unknown Source)
at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tryprasannan** [comment]
@rachitmishra Thanks for reporting. Can you please share the version of Hotline SDK you're facing this on ?

**Comment by rachitmishra** [comment]
1.0.15

**Comment by tryprasannan** [comment]
@rachitmishra Thanks for sharing the version number. We'll look into this and share an update.

**Comment by hrishikesh-p** [comment]
This leak has been fixed now.
