### ISSUE TITLE
DatabaseObjectNotClosedException

### ISSUE THREAD

**Issue by yokeshezumalai** [freshdesk/hotline-android#2]
Finalizing a Cursor that has not been deactivated or closed - Hotline DB, but i have cleared the user data using the following code- Hotline.clearUserData(getApplicationContext()) as explained in the document. Can anyone tell me how to close the db and where to close the db.

**Comment by hrishikesh-p** [comment]
@Yokeshthebouncer  We manage the DB within the SDK and you don't have to close the DB. Are you seeing any exception or error ? Can you please share the stack trace  or log , if any ? 

You need to call `clearUserData` only when a different user logs in to make sure the new user doesn't see the previous user's data.

**Comment by yokeshezumalai** [comment]
No need to call clearUserData, because my app will be used by single user. I'm getting following strict mode error, please see the log below,

05-04 14:14:16.661 3328-3341/com.wassup.laundry1 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'end' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                   at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                   at com.android.okio.GzipSource.<init>(GzipSource.java:57)
                                                                   at com.android.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:490)
                                                                   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:680)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
                                                                   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                   at com.demach.konotor.client.helper.a.a(Unknown Source)
                                                                   at com.demach.konotor.client.helper.a.r(Unknown Source)
                                                                   at com.freshdesk.hotline.service.helper.e.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.n.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.n.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.executor.b.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
05-04 14:14:16.675 3328-3341/com.wassup.laundry1 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                   at android.database.CursorWindow.<init>(CursorWindow.java:111)
                                                                   at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                                                                   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
                                                                   at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                   at com.freshdesk.hotline.db.b.cO(Unknown Source)
                                                                   at com.freshdesk.hotline.service.helper.a.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.helper.a.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.d.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.d.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.executor.b.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
05-04 14:14:16.677 3328-3341/com.wassup.laundry1 E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/data/com.wassup.laundry1/databases/hotline.db, table = channels, query = SELECT _id, name, position, icon, hidden, type FROM channels WHERE hidden=0
                                                               android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                   at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:98)
                                                                   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
                                                                   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                   at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                   at com.freshdesk.hotline.db.b.cO(Unknown Source)
                                                                   at com.freshdesk.hotline.service.helper.a.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.helper.a.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.d.a(Unknown Source)
                                                                   at com.freshdesk.hotline.service.handler.d.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.executor.b.b(Unknown Source)
                                                                   at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)

**Comment by hrishikesh-p** [comment]
@Yokeshthebouncer This helps .. We will have it fixed in the next update.

**Comment by yokeshezumalai** [comment]
ok thank you.

**Comment by hrishikesh-p** [comment]
This has been fixed in 1.0.10 and no new issues reported.
