### ISSUE TITLE
File URI exposed exception

### ISSUE THREAD

**Issue by PankajRaincan** [freshdesk/hotline-android#21]
I have integrated hotline in my application but it is randomely crashing at this point

logs--
android.os.FileUriExposedException: 
  at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
  at android.net.Uri.checkFileUriExposed(Uri.java:2346)
  at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
  at android.content.Intent.prepareToLeaveProcess(Intent.java:8948)
  at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
  at android.app.Activity.startActivityForResult(Activity.java:4317)
  at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
  at android.app.Activity.startActivityForResult(Activity.java:4276)
  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
  at com.freshdesk.hotline.activity.ConversationDetailActivity.aK(Unknown Source:0)
  at com.freshdesk.hotline.activity.ConversationDetailActivity.d(Unknown Source:0)
  at com.freshdesk.hotline.activity.af.onClick(Unknown Source:0)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1119)
  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1202)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3189)
  at android.widget.AbsListView$3.run(AbsListView.java:4243)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6317)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by tryprasannan** [comment]
@PankajRaincan Sorry missed this earlier. Can you please confirm your SDK version ?  Also can you confirm if you have followed the steps for adding support for FileProvider when targeting Android 7.0  from the [integration guide](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps/#android_24) ?

**Comment by PankajRaincan** [comment]
Yes followed the steps and fixed the bug,Thnx for the input
