### ISSUE TITLE
Crashing when clicked on conversations

### ISSUE THREAD

**Issue by chaitanya-exp** [freshdesk/hotline-android#23]
On Version 1.2.3 with custom theme, when clicked on channel to see a conversation the following crash occurs [Device version 7.0].

```06-14 11:38:21.638  1609  1654 I ActivityManager: START u0 {cmp=com.practo.fabric/com.freshdesk.hotline.activity.ConversationDetailActivity (has extras)} from uid 10111 on display 0
06-14 11:38:21.824  9157  9157 D AndroidRuntime: Shutting down VM
06-14 11:38:21.839  9157  9157 E AndroidRuntime: FATAL EXCEPTION: main
06-14 11:38:21.839  9157  9157 E AndroidRuntime: Process: com.practo.fabric, PID: 9157
06-14 11:38:21.839  9157  9157 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.practo.fabric/com.freshdesk.hotline.activity.ConversationDetailActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #7: Error inflating class ImageView
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #31: Binary XML file line #7: Error inflating class ImageView
06-14 11:38:21.839  9157  9157 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class ImageView
06-14 11:38:21.839  9157  9157 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010009 a=-1}
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.View.<init>(View.java:4175)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:150)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:145)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at com.freshdesk.hotline.activity.ConversationDetailActivity.onCreate(Unknown Source)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6662)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-14 11:38:21.839  9157  9157 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-14 11:38:21.847  1609  2194 W ActivityManager:   Force finishing activity com.practo.fabric/com.freshdesk.hotline.activity.ConversationDetailActivity
06-14 11:38:21.858  1609  2194 W ActivityManager:   Force finishing activity com.practo.fabric/com.freshdesk.hotline.activity.ChannelListActivity```

**Comment by chaitanya-exp** [comment]
The same crash on 4.4.2

``` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.practo.fabric/com.freshdesk.hotline.activity.ConversationDetailActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class ImageView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class ImageView
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                     at com.freshdesk.hotline.activity.ConversationDetailActivity.onCreate(Unknown Source)
                                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010009 a=-1}
                                                                     at android.content.res.Resources.loadDrawable(Resources.java:2073)
                                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                     at android.view.View.<init>(View.java:3554)
                                                                     at android.widget.ImageView.<init>(ImageView.java:123)
                                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
                                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
                                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                     at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                     at com.freshdesk.hotline.activity.ConversationDetailActivity.onCreate(Unknown Source) 
                                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) ```

**Comment by tryprasannan** [comment]
@chaitanya-exp Can you help us with the custom theme you are using that causes this ?

**Comment by tryprasannan** [comment]
@chaitanya-exp Without the custom theme, we are unable to debug this issue. Please let us know if you are still facing this issue ? If yes, please share the custom theme you are using that causes this issue?

**Comment by tryprasannan** [comment]
@chaitanya-exp We're closing this as this can't be debugged without the custom theme. If you're still facing this, please reopen and share the custom theme.
