### ISSUE TITLE
No Such Element Exception

### ISSUE THREAD

**Issue by PankajRaincan** [freshdesk/hotline-android#24]
java.util.NoSuchElementException: 
  at java.util.LinkedList.removeFirstImpl(LinkedList.java:689)
  at java.util.LinkedList.remove(LinkedList.java:899)
  at com.freshdesk.hotline.service.HotlineService.onHandleIntent(Unknown Source:0)
  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tryprasannan** [comment]
@PankajRaincan Can you please confirm the version this is happening on ? If you're on older versions, we recommend upgrading to the latest version

**Comment by PankajRaincan** [comment]
I'm on 1.2.3

**Comment by tryprasannan** [comment]
@PankajRaincan Is this causing a crash or are you just noticing the logs being printed ? Also can you share more information from logs including the log tag and an additional lie Hotline SDK prints which include manufacturer, model, os version etc

**Comment by PankajRaincan** [comment]
I saw the crash log on google play developers console
Android version-Android 5.0
Device-Galaxy S4 (ja3g)
Manufacturer-Samsung
RAM (MB)- 2048
Screen size-1080 × 1920
Screen density (dpi)-480
Native platform-armeabi-v7a
OpenGL ES version-2.0
CPU make-Samsung
CPU model-Exynos 5410

**Comment by tryprasannan** [comment]
@PankajRaincan Can you check and let us know what version of the app (and hence Hotline SDK) this particular user was on ? This was indeed an issue in an old versions and got fixed in version 1.0.8 of SDK.
