### ISSUE TITLE
java.lang.NullPointerException in faq

### ISSUE THREAD

**Issue by Vatreni** [freshdesk/hotline-android#25]
Hi, I'm using your library v.1.2.3 and faced with this crash while using faq on Sony Xperia M2 (Android 4.3)          java.lang.NullPointerException
	at android.webkit.WebViewClassic.sendOurVisibleRect(WebViewClassic.java:3174)
	at android.webkit.WebViewClassic.onScrollChanged(WebViewClassic.java:5718)
	at android.webkit.WebView.onScrollChanged(WebView.java:2154)
	at com.freshdesk.hotline.activity.ao.onScrollChanged(Unknown Source)
	at android.view.View.scrollTo(View.java:10391)
	at com.freshdesk.hotline.activity.b.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5214)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by tryprasannan** [comment]
@Vatreni Thanks for reporting this. From the stack trace it looks like this is happening on FAQ detail screen, do you know when and how often this is happening on FAQ detail screen or any other information that can help us reproduce this issue?

**Comment by Vatreni** [comment]
@tryprasannan Sure,
1. Start Hotline screen via Hotline.showFAQs
2. Select General category
3. Select one of the subcategories
4. Tap Back at once, !don't wait until data loads like as if you don't want to select this subcategory
5. Repeat steps 2-4 until app crashes
Also this crash can be reproduced on Samsung Galaxy Nexus (4.3)

**Comment by tryprasannan** [comment]
@Vatreni Thanks for the information. We'll try to reproduce this issue from our end and update you on the status.
