### ISSUE TITLE
Its getting crashed due to use of ActionBarActivity in your library when app is uses latest support library(v26.0.0) at the time  of writing

### ISSUE THREAD

**Issue by bhaveshopenxcell** [freshdesk/hotline-android#27]
Hello It seems app is providing below crash when app is running with latest support library(v26.0.0) with customized them.

**Please Note:** Its working absolutely fine when it uses last stable version 25.4.0 in my app.

Error for your reference:

`FATAL EXCEPTION: main
                                                           Process: com.cheep, PID: 25356
                                                           java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/InterstitialActivity;
                                                               at com.freshdesk.hotline.util.ar.eY(Unknown Source)
                                                               at com.freshdesk.hotline.util.ar.eT(Unknown Source)
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source)
                                                               at com.cheep.utils.HotlineHelper.showConversation(HotlineHelper.java:71)
                                                               at com.cheep.fragment.FAQFragment$2.onClick(FAQFragment.java:137)
                                                               at android.view.View.performClick(View.java:5637)
                                                               at android.view.View$PerformClick.run(View.java:22429)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                            Caused by: java.lang.ClassNotFoundException: com.freshdesk.hotline.activity.InterstitialActivity
                                                               at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                               at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                               at com.freshdesk.hotline.util.ar.eY(Unknown Source) 
                                                               at com.freshdesk.hotline.util.ar.eT(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.cheep.utils.HotlineHelper.showConversation(HotlineHelper.java:71) 
                                                               at com.cheep.fragment.FAQFragment$2.onClick(FAQFragment.java:137) 
                                                               at android.view.View.performClick(View.java:5637) 
                                                               at android.view.View$PerformClick.run(View.java:22429) 
                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                            Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
                                                               at com.freshdesk.hotline.util.ar.eY(Unknown Source) 
                                                               at com.freshdesk.hotline.util.ar.eT(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.cheep.utils.HotlineHelper.showConversation(HotlineHelper.java:71) 
                                                               at com.cheep.fragment.FAQFragment$2.onClick(FAQFragment.java:137) 
                                                               at android.view.View.performClick(View.java:5637) 
                                                               at android.view.View$PerformClick.run(View.java:22429) 
                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.ActionBarActivity" on path: DexPathList[[zip file "/data/app/com.cheep-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cheep-1/lib/x86_64, /data/app/com.cheep-1/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                               at com.freshdesk.hotline.util.ar.eY(Unknown Source) 
                                                               at com.freshdesk.hotline.util.ar.eT(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.freshdesk.hotline.Hotline.showConversations(Unknown Source) 
                                                               at com.cheep.utils.HotlineHelper.showConversation(HotlineHelper.java:71) 
                                                               at com.cheep.fragment.FAQFragment$2.onClick(FAQFragment.java:137) 
                                                               at android.view.View.performClick(View.java:5637) 
                                                               at android.view.View$PerformClick.run(View.java:22429) 
                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

It seems library uses ActioBarActivity class which is been removed now. It should use AppCompatActivity instead.

**Comment by tryprasannan** [comment]
@bhaveshopenxcell Thanks for reporting this. The SDK references the old name for maintaining compatibility with applications still targetting older versions of Android. We'll look at ways to support this.

**Comment by tryprasannan** [comment]
@bhaveshopenxcell We'll look at ways to address this as part of our next release. Meanwhile if you want to target Android O and build with support lib 26.x.x, we recommend creating a proxy class manually. i.e. create the class **ActionBarActivity** with the same package name as it is present in support library and extend **AppCompatActivity** and include this in your project and it should work.

**Comment by bhaveshopenxcell** [comment]
Kindly keep this on High priority as its something which would restrict us targeting the app to latest SDK version. Talking about the workaround you suggested is obviously not the proper solution.

**Comment by tryprasannan** [comment]
@bhaveshopenxcell When building with Oreo as Target, please follow our [ integration guide ](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android8) for making it compatible with Oreo. If this still doesn't work for you, please reach out to us at support@hotline.io or reply here.

**Comment by nitinnatural** [comment]
create a package inside **yourApp>src>main>java** package with name:
**android.support.v7.app**

Inside that create a **class ActionBarActivity** which extends **AppCompatActivity**

then it should work.
