### ISSUE TITLE
Hotline.jar uses the support v7 22.2.1

### ISSUE THREAD

**Issue by RahulJanagouda** [freshdesk/hotline-android#28]
Hey @tryprasannan 
After forking, I tried making your SDK compatible to latest _Android Studio 3.0 with Gradle plugin 3_ support, Also with new support library and play services. **But since your hotline.jar bundled in the SDK libs uses v7:22.2.1**, (this might be to support Android 10+) I guess you need to maintain two branches to supporting latest and 10+ sdks. 
Let us know... We are currently converting our app to _Android Studio 3 and Gradle Plugin 3_ support **we are kinda stuck because of this**. Please find the enclosed dependency tree

Thanks

![screen shot 2017-07-26 at 12 44 07 pm](https://user-images.githubusercontent.com/2093518/28609016-7fbad058-7200-11e7-8eed-efcd55787f82.png)

**Comment by tryprasannan** [comment]
@RahulJanagouda We do support older versions of Android and hence older support lib is default, but can work with newer versions upto 25.x.x. Android Studio 3.0 with Plugin 3.0 may not be the issue so much as the support v7 revision 26.0.x. Can you try with 25.x.x ?

**Comment by tryprasannan** [comment]
@RahulJanagouda We'll look at ways to address this as part of our next release. Meanwhile if you want to target Android O and build with support lib 26.x.x, we recommend creating a proxy class manually. i.e. create the class **ActionBarActivity** with the same package name as it is present in support library and extend **AppCompatActivity** and include this in your project and it should work.

**Comment by kaseyb002** [comment]
Here is my newly created ActionBarActivity.kt:

```
package com.android.support.v7.app

import android.support.v7.app.AppCompatActivity

class ActionBarActivity: AppCompatActivity() {}
```

Is this what you suggested? I still get the following error:


```
FATAL EXCEPTION: main
                                                                                      Process: com.freshapps.kaseybaughan.emotioncode, PID: 7320
                                                                                      java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/am;
                                                                                          at com.freshdesk.hotline.util.l.a(Unknown Source)
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source)
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source)
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment.goToFAQ(SupportFragment.kt:24)
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.doResume(SupportFragment.kt:18)
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:0)
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:13)
                                                                                          at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285)
                                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                                          at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171)
                                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                                       Caused by: java.lang.ClassNotFoundException: com.freshdesk.hotline.activity.am
                                                                                          at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                          at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                          at com.freshdesk.hotline.util.l.a(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment.goToFAQ(SupportFragment.kt:24) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.doResume(SupportFragment.kt:18) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:0) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:13) 
                                                                                          at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285) 
                                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
                                                                                          at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171) 
                                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                                                       Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/l;
                                                                                          at com.freshdesk.hotline.util.l.a(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment.goToFAQ(SupportFragment.kt:24) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.doResume(SupportFragment.kt:18) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:0) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:13) 
                                                                                          at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285) 
                                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
                                                                                          at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171) 
                                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                                                       Caused by: java.lang.ClassNotFoundException: com.freshdesk.hotline.activity.l
                                                                                          at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                          at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                          at com.freshdesk.hotline.util.l.a(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment.goToFAQ(SupportFragment.kt:24) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.doResume(SupportFragment.kt:18) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:0) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:13) 
                                                                                          at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285) 
                                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
                                                                                          at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171) 
                                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                                                       Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
                                                                                          at com.freshdesk.hotline.util.l.a(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshdesk.hotline.Hotline.showFAQs(Unknown Source) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment.goToFAQ(SupportFragment.kt:24) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.doResume(SupportFragment.kt:18) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:0) 
                                                                                          at com.freshapps.kaseybaughan.emotioncode.SupportFragment$onCreateView$1.invoke(SupportFragment.kt:13) 
                                                                                          at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285) 
                                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
                                                                                          at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171) 
                                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.ActionBarActivity" on path: DexPathList[[zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/base.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.freshapps.kaseybaughan.emotioncode-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.freshapps.kaseybaughan.emotioncode-1/lib/x86, /system/lib, /vendor/lib]]
                                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by kaseyb002** [comment]
Reverted back to v25 and now it is working.

**Comment by tryprasannan** [comment]
With 26.x.x, we tested with the proxy class in java and verified it works fine. In fact appcompat-v7 lib itself was shipping ActionBarActivity as a proxy class since introduction of AppCompatActivity. 
Refer [here for more info](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android8).
