### ISSUE TITLE
OutOfMemoryError in Hotline's AsyncTask

### ISSUE THREAD

**Issue by vibin** [freshdesk/hotline-android#33]
What the title says. Stacktrace below: 
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:922)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:895)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:827)
       at com.freshdesk.hotline.tasks.l.doInBackground(Unknown Source)
       at com.freshdesk.hotline.tasks.l.doInBackground(Unknown Source)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```
I tried reproducing it by uploading high resolution images (and taking pictures) in conversation view, but that didn't work.

**Comment by vibin** [comment]
Anything on this?

**Comment by tryprasannan** [comment]
@vibinr We haven't been able to reproduce this issue. Was this on when taking pictures or selecting pictures from gallery ? Do you have more information about the device ? Wondering if it's a device with camera producing particularly large images.

**Comment by vibin** [comment]
I'm not sure. Some info related to devices here (grabbed from Crashlytics), also including the activity stack of our app when it crashed: [hotline_oom.txt](https://github.com/freshdesk/hotline-android/files/1363056/hotline_oom.txt)

(*main.MainActivity* is an Activity from our app, rest all are from Hotline SDK)

**Comment by vibin** [comment]
We've seen quite a bit of decrease in OOMs in recent app versions (also, actually we had many different OOM stacktraces) - so I'm guessing Hotline has nothing to do with it.

Sorry for the noise!
