### ISSUE TITLE
NoClassDefFoundError in v1.2.6

### ISSUE THREAD

**Issue by kshitij-sminq** [freshdesk/hotline-android#36]
Please check this. I'm not able to update my app to API 26 because of Hotline.
Hotline 1.2.6
compileSdkVersion 26
buildToolsVersion "26.0.3"
supportLibraryVersion = "26.1.0"

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/l;
                                                                       at com.freshdesk.hotline.util.t.a(Unknown Source)
                                                                       at com.freshdesk.hotline.Hotline.setNotificationConfig(Unknown Source)
```

**Comment by AmitBarjatya** [comment]
Were you able to find a solution for this?
I am facing a similar issue while upgrading sdk to 1.2.6 from 1.2.2 (my compile sdk is 22)

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/hotline/activity/InterstitialActivity;

**Comment by kshitij-sminq** [comment]
No. It seems they have stopped development and support for Hotline.

**Comment by AmitBarjatya** [comment]
Yeah, that they did.
You might want to see this [link](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android8). It solved the crash for me but still facing the issue with some proguard config tho.
